### ISSUE TITLE
Permission denied @ rb_sysopen

### ISSUE THREAD

**Issue by netzwerkgoettin** [ghoneycutt/puppet-module-ssh#227] opened 2017-05-20 20:00 UTC
Hi,

I try to manage authorized_keys via Puppet. So I have a Debian.yaml for all Debian based hosts and the following config:

```
ssh::keys:
  root_on_host:
    ensure: present
    user: root
    type: rsa
    key: AAAA...
```

A specific node gets additional config - here's the user "testuser", and he should get a key, too. 

```
ssh::keys:
  testuser_on_node:
    ensure: present
    user: testuser
    type: rsa
    key: AAAA...
```

Assuming root and testuser have no authorized_key file, my puppet run succeeds:
````
$ puppet agent --test
...
Notice: /Stage[main]/Ssh/Ssh_authorized_key[testuser_on_node]/ensure: created
Notice: /Stage[main]/Ssh/Ssh_authorized_key[root_on_host]/ensure: created
Notice: Applied catalog in 0.37 seconds
````

But the second run - or every run, when authorized_keys files already exist - fails with error:
```
...
Notice: /Stage[main]/Ssh/Ssh_authorized_key[testuser_on_node]/user: user changed 'root' to 'testuser'
Notice: /Stage[main]/Ssh/Ssh_authorized_key[testuser_on_node]/target: target changed '/root/.ssh/authorized_keys' to '/home/testuser/.ssh/authorized_keys'
Info: Computing checksum on file /home/testuser/.ssh/authorized_keys
Error: Puppet::Util::FileType::FileTypeFlat could not write /root/.ssh/authorized_keys: Permission denied @ rb_sysopen - /root/.ssh/authorized_keys
```

What is going wrong there? (Or: what I'm doing wrong? :) ) When I disable all keys in node config, puppet run succeeds again. I'm using ghoneycutt-ssh (v3.51.0).

Cheers,
  Marianne

**Comment by ghoneycutt** [comment] 2017-05-20 21:06
Are you running puppet as the root user? Does this still happen if you run from the root directory? `[root@host]# cd / && puppet agent -t`

**Comment by sysadmama** [comment] 2017-05-20 21:09
Yes. And running it from / makes no difference...

**Comment by ghoneycutt** [comment] 2017-05-20 21:20
Are you on an NFS filesystem or another network based filesystem?

**Comment by ghoneycutt** [comment] 2017-05-20 21:38
I'm not able to reproduce the issue. The problem appears to be with file system permissions and not the module. Which version of puppet and ruby do you have? What is the output of `mount`? What OS version is this?

Running with more information might help - `puppet agent -t -d --trace`

**Comment by sysadmama** [comment] 2017-05-21 11:45
Hi,

OS => Debian Jessie 3.16.0-4-amd64
No NFS, only a GlusterFS share for backups
Puppet version 4.10.1
Ruby 2.1.5-2

In fact, it seems to be node issue: on other nodes, everything works fine. On the failing node, I notice the message

```
Notice: /Stage[main]/Ssh/Ssh_authorized_key[testuser_on_node]/user: user changed 'root' to 'testuser'
```

This message does not appear on the other (working) nodes. Could it be a problem that the failing node is both, puppetserver **and** agent?

Cheers,
  Marianne

````
Error: Puppet::Util::FileType::FileTypeFlat could not write /root/.ssh/authorized_keys: Permission denied @ rb_sysopen - /root/.ssh/authorized_keys
/opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:1402:in `initialize'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:1402:in `open'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:1402:in `block in copy_file'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:1401:in `open'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:1401:in `copy_file'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:483:in `copy_file'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:400:in `block in cp'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:1579:in `block in fu_each_src_dest'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:1595:in `fu_each_src_dest0'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:1577:in `fu_each_src_dest'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/fileutils.rb:399:in `cp'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/filetype.rb:127:in `write'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/filetype.rb:58:in `block (2 levels) in newfiletype'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/provider/parsedfile.rb:98:in `flush_target'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/provider/parsedfile.rb:71:in `block in flush'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/provider/parsedfile.rb:68:in `each'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/provider/parsedfile.rb:68:in `flush'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/provider/parsedfile.rb:428:in `flush'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/provider/ssh_authorized_key/parsed.rb:65:in `block in flush'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/suidmanager.rb:72:in `asuser'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/provider/ssh_authorized_key/parsed.rb:59:in `flush'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/type.rb:1006:in `flush'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/resource_harness.rb:25:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:230:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:246:in `eval_resource'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:163:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:163:in `block (2 levels) in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:387:in `block in thinmark'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:386:in `thinmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:163:in `block in evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/graph/relationship_graph.rb:118:in `traverse'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction.rb:154:in `evaluate'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:222:in `block in apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/log.rb:155:in `with_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/transaction/report.rb:142:in `as_logging_destination'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/resource/catalog.rb:221:in `apply'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:171:in `block in apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:224:in `block in benchmark'
/opt/puppetlabs/puppet/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:223:in `benchmark'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:170:in `apply_catalog'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:343:in `run_internal'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:221:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/context.rb:65:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet.rb:294:in `override'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/configurer.rb:195:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:45:in `block (4 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent/locker.rb:21:in `lock'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:45:in `block (3 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:98:in `with_client'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:42:in `block (2 levels) in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:65:in `run_in_fork'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:41:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:179:in `call'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:179:in `controlled_run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/agent.rb:39:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:353:in `onetime'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application/agent.rb:331:in `run_command'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:358:in `block in run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util.rb:542:in `exit_on_fail'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/application.rb:358:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:132:in `run'
/opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/util/command_line.rb:72:in `execute'
/opt/puppetlabs/puppet/bin/puppet:5:in `<main>'
```

**Comment by ghoneycutt** [comment] 2017-05-22 14:27
It is failing here

```Error: Puppet::Util::FileType::FileTypeFlat could not write /root/.ssh/authorized_keys: Permission denied @ rb_sysopen - /root/.ssh/authorized_keys```

because it cannot write to that file. Not sure why. It doesn't have anything to do with it being a puppetserver.

**Comment by ramamaddodi** [comment] 2018-02-16 22:05
Hi @ghoneycutt : I started seeing same issue on my end with user accounts. I added sshkeys under authorized_keys but its seems mentioned keys are owned by root and permission on it is set to 600. Because of which users cannot log in to the server (as they don't own key nor they have read permission on authorized_key).  I changed $user from root to $user but it throwing mentioned error message 

Info: Computing checksum on file /var/.ssh/testuser/authorized_keys
Error: Puppet::Util::FileType::FileTypeFlat could not write /var/.ssh/testuser/authorized_keys: Permission denied @ rb_sysopen - /var/.ssh/testuser/authorized_keys
Error: : Could not evaluate: Puppet::Util::FileType::FileTypeFlat could not write /var/.ssh/testuser/authorized_keys: Permission denied @ rb_sysopen - /var/.ssh/testuser/authorized_keys

**Comment by dietmarb01** [comment] 2018-05-04 20:07
I had a similar issue when trying to write keys to a central location. The fix was to specify the user as 'root' instead of the user for whom the keys are, because 'root' is the true owner of the file (we want the file to be protected from modifications by the user!). 
It seems that Puppet temporarily changes its uid to the target user.
```
      # Add authorized keys to central location
      # /etc/ssh/sshd_config: 
      #   AuthorizedKeysFile /etc/ssh/authorized_keys/%u
      $key_file  = "${authorized_keys_root}/${user}"
       ...
      ssh_authorized_key { $key_title:
        ensure    => $ensure,
        user      => 'root',    # !!! protected !!!
        name      => $key_name,
        key       => $key_content,
        type      => $key_type,
        options   => $key_options,
        target    => $key_file,
      }
```

**Comment by rick-pri** [comment] 2018-07-16 15:32
Okay, I have been having this on `GCP` and the issue is that `GCP` creates accounts which just so happen to be named the same as the accounts that puppet controls and had done this before puppet had run for the first time (we have auto signing setup).  We'd specified the `uid`s for these accounts and puppet was coming along and changing the user's `uid` and although `managehome` was set the `.ssh` directory still had the old `uid` value as the `owner` ... puppet had changed the ownership of the home directory and everything in it **_except_** for the `.ssh` directory.  `chown`ing the user's `.ssh` dir to the correct `uid` and running puppet and the errors vanished and the users were provisioned.  

I've taken the easy option and removed the specific `uid`s rather than having to write a required file resource which ensures that the `uid` is correct on the `.ssh` before trying to put the folder in place but I'd guess that that might work too.

**Comment by ghoneycutt** [comment] 2023-04-06 17:14
Closing due to age. The module has undergone a major release and now supports every documented configuration parameter for OpenSSH. The module also allows for custom entries to future proof functionality and support other SSH implementations. See [UPGRADING.md](https://github.com/ghoneycutt/puppet-module-ssh/blob/main/UPGRADING.md).

**Closed by ghoneycutt** 2023-04-06 17:14 UTC
