### ISSUE TITLE
Puppet The string '7' was automatically coerced to the numerical value 7

### ISSUE THREAD

**Issue by linuxphone** [ghoneycutt/puppet-module-ssh#285] opened 2018-09-05 17:12 UTC
Guys,
I am getting the following WARN on every node rune:

Puppet The string '7' was automatically coerced to the numerical value 7 (file: /etc/puppetlabs/code/environments/development/modules/ssh/manifests/init.pp, line: 291, column: 33)

Puppet The string '4' was automatically coerced to the numerical value 4 (file: /etc/puppetlabs/code/environments/development/modules/ssh/manifests/init.pp, line: 292, column: 32)

I am running puppet agent 5.5 and RHEL 7.5

**Comment by linuxphone** [comment] 2018-09-05 17:13
This is the impacted lines under init.pp

    $ssh_version_maj_int = (0 + ($ssh_version_array[0]))
    $ssh_version_min_int = 0 + $ssh_version_array[1]

**Comment by ghoneycutt** [comment] 2018-09-06 16:36
We are purposely changing the value to an integer so that we can use comparison operators on those numbers. Do you have another solution?

https://github.com/ghoneycutt/puppet-module-ssh/blob/master/manifests/init.pp#L293-L295

**Comment by linuxphone** [comment] 2018-09-08 14:01
ghoneycutt, I am not sure on solution...are we getting a change push for this soon, if so, what would be the estimated timeframe to see this WARN gone. Please advise.

**Comment by TheMeier** [comment] 2019-04-17 10:42
voxpupuli and puppet stdlib are starting to raise their minimum puppet requirement to <= 5.5.10. Maybe it is finally the time to ditch support for old puppet versions and use data types.

**Comment by ghoneycutt** [comment] 2019-04-17 19:09
@TheMeier Check out PR #307 where I'm working on just that :)

**Comment by jonhattan** [comment] 2019-09-10 12:45
Here's a fix, as seen at https://github.com/puppetlabs/puppetlabs-apt/pull/743/files
`$ssh_version_min_int = Integer($ssh_version_array[1])`

**Comment by Phil-Friderici** [comment] 2023-01-31 13:38
Closing this as the issue is fixed in v4.
Please re-open if this doesn't fix your use case.

**Closed by Phil-Friderici** 2023-01-31 13:38 UTC
