### ISSUE TITLE
ssh module custom fact error

### ISSUE THREAD

**Issue by andrewkzimmerman** [ghoneycutt/puppet-module-ssh#249] opened 2017-10-04 11:58 UTC
I am getting the following error when running puppet agent -t on a client server (RHEL 6) using the ghoneycutt/ssh module. Attached is my init.pp.
[init.pp.txt](https://github.com/ghoneycutt/puppet-module-ssh/files/1355667/init.pp.txt)

Error: Facter: error while resolving custom fact "ssh_version_numeric": undefined method `[]' for nil:NilClass

**Comment by ghoneycutt** [comment] 2017-10-04 14:53
What's the output of `ssh -V`

**Comment by andrewkzimmerman** [comment] 2017-10-04 14:58
OpenSSH_5.3p1, OpenSSL 1.0.1e-fips

/r,
Andrew K. Zimmerman
Contractor
JRSS Tier III JMS Engineer
DISA JFHQ-DODIN
301-225-9860

--Unclassified--

-----Original Message-----

**Comment by ghoneycutt** [comment] 2017-10-04 15:50
I am unable to reproduce the error. It seems that the fact is not resolving correctly, though I tested with the string you provided and the facts `ssh_version` and `ssh_version_numeric` resolved as expected.

Are you using the latest version of this module?

**Comment by andrewkzimmerman** [comment] 2017-10-04 16:04
Using ghoneycutt-ssh-3.55.0.tar.gz downloaded 9/29/2017

**Comment by ghoneycutt** [comment] 2017-10-04 16:09
What platform are you running on? How could I reproduce this issue?

**Comment by andrewkzimmerman** [comment] 2017-10-04 16:13
I am using PE 2017.2 on RHEL7 with clients on RHEL 6.9.

I see in the init.pp ssh_version_numeric is in an if statement. I can also see it is in spec/classes/init_spec.rb and spec/unit/facter/ssh_spec.rb and in lib/facter/ssh.rb. What code is actually running the check on the client and then passing the string on? If I get that I can probably find the issue.

**Comment by andrewkzimmerman** [comment] 2017-10-04 16:15
If I can't resolve the issue today I will uninstall and reinstall the module to see If I get a different result.

**Comment by andrewkzimmerman** [comment] 2017-10-04 17:43
I uninstalled and reinstalled then ran the agent on the client. It ran through this time, but It did still output the same error in the output when the agent ran. But the deployment of the puppet configured file was set on the client. I guess the issue can be closed.

**Closed** 2017-10-04 19:41 UTC
